### ISSUE TITLE
COVID-19: masculin ou féminin?

### ISSUE THREAD

**Issue by sylvainberube** [cyrilou242/covid-19#12]
Pour l'instant, le masculin a été privilégié dans la traduction pour désigner le/la COVID-19. Toutefois selon [cette référence](http://gdt.oqlf.gouv.qc.ca/ficheOqlf.aspx?Id_Fiche=26557671) de l'Office québécois de la langue française, le terme serait féminin. Au Canada le gouvernement et les médias utilisent principalement le féminin. C'est peut-être différent ailleurs sur le globe.

**Comment by e-guenat** [comment]
Pour la Suisse francophone -où je vis- , la forme masculine est quasi-exclusivement utilisée dans les médias et par la population, tout comme cela semble être le cas en France. Je suis pour maintenir cette forme.

**Comment by cyrilou242** [comment]
haha j'attendais les différences quebec - europe francophone. 
Je propose qu'on garde le masculin aussi, et fork version quebecoise à la fin

**Comment by NicoKiaru** [comment]
https://www.reddit.com/r/france/comments/g3q8ei/la_v%C3%A9ritable_guerre_dont_personne_ne_parle/

;-)

Le blog des correcteurs du monde dit 'le Covid' mais ils ne sont pas penchés explicitement sur la question : https://www.lemonde.fr/blog/correcteurs/tag/covid-19/

Sinon il y a cet article qui regarde ça en détail : https://www.franceculture.fr/sciences-du-langage/doit-dire-le-ou-la-covid-19

**Comment by sylvainberube** [comment]
« La guerre dont personne ne parle » 😂

Ça me va de conserver le masculin, quitte à produire un fork en québécois à la fin.
