### ISSUE TITLE
Traduction : Mitigation et Suppression

### ISSUE THREAD

**Issue by NicoKiaru** [cyrilou242/covid-19#13]
Ces mots apparaissent chacun trois fois dans le texte  (et dans les images) .

Ce sont des termes importants...

Vous avez trouvé les bonnes traductions ?

Il faudrait trouver les vrais termes en français, regarder des docs d'épidémiologie.

Sur cet article (https://www.lexpress.fr/actualite/societe/sante/coronavirus-pourquoi-l-oms-ne-vise-plus-l-endiguement-mais-l-attenuation-de-l-epidemie_2119203.html), j'ai l'impression qu'on a:

* mitigation = atténuation
* suppression = endiguement

A confirmer sur d'autres sources

**Comment by e-guenat** [comment]
Je n'ai pas trouvé mieux que toi comme traduction, malheureusement je n'ai pas trouvé d'autre références solides. Je pars sur cette traduction pour l'instant.

**Comment by NicoKiaru** [comment]
Ca doit etre ok effectivement, j'ai trouvé une autre source qui fait explicitement cette traduction:

> Ces deux options sont qualifiées de « mitigation » (atténuation) et de « suppression » (endiguement)

https://www.lemonde.fr/sciences/article/2020/03/17/covid-19-les-scenarios-decisifs-de-modelisateurs-britanniques_6033393_1650684.html

**Comment by MaximeBedoin** [comment]
Ok
