### ISSUE TITLE
Aplatir / Aplanir ?

### ISSUE THREAD

**Issue by e-guenat** [cyrilou242/covid-19#17]
Je vois des deux un peu partout. Votre avis ?

**Comment by NicoKiaru** [comment]
Aplatir sur le site du monde:

https://www.lemonde.fr/les-decodeurs/article/2020/03/27/coronavirus-visualisez-les-pays-qui-ont-aplati-la-courbe-de-l-infection-et-ceux-qui-n-y-sont-pas-encore-parvenus_6034627_4355770.html

Ils mettent des guillemets cependant.

Les deux paraissent ok.

**Comment by e-guenat** [comment]
OK, alors je continue avec aplatir

**Comment by MaximeBedoin** [comment]
Ok
