### ISSUE TITLE
Watch pout tout le monde!

### ISSUE THREAD

**Issue by NicoKiaru** [cyrilou242/covid-19#19]
Hello @MaximeBedoin, @sylvainberube, @e-guenat,

J'avais oublié de le faire, donc je le signale au cas ou ca vous serve : cliquez sur Watch en haut de la page de @cyrilou242 pour suivre les modifications et les issue en cours.

++ bonne journée

**Comment by sylvainberube** [comment]
@NicoKiaru Tu m'apprends un truc sur Github, merci!

**Comment by donok1** [comment]
Hello à tous, et merci @cyrilou242 pour l'organisation.
Je donne volontiers un coup de main pour les relectures, puisque la plupart des traductions sont déjà terminées.
