### ISSUE TITLE
Ecriture inclusive ?

### ISSUE THREAD

**Issue by e-guenat** [cyrilou242/covid-19#2]
C'est un sujet d'importance croissante pour lequel la question mérite d'être posée : Utiliserons-nous l'écriture inclusive (voir un petit [guide](https://www.hepl.ch/files/live/sites/systemsite/files/instance-egalite/manuel-ecriture-inclusive-2016.pdf)) pour lever l'ambiguïté typique des traduction anglais vers français ?

Je suis typiquement tombé sur ce problème dans le chapitre _Next Years_, par exemple:

>  And write your local **policymaker** to get off their butt and...

Ici, choisir le masculin serait arbitraire. Plus juste serait -à mon avis- d'utiliser une forme inclusive, ce qui donnerait **décideur·euse·s**.

Qu'en pensez-vous ?

**Comment by cyrilou242** [comment]
Perso je suis contre. Je suis aujourd'hui incapable d'écrire correctement en inclusif (sans grosse charge cognitive du moins).
Pas de problèmes en post-édition à la fin, ou sinon un fork tout de suite en inclusif first, auquel je ne participerai pas.

**Comment by e-guenat** [comment]
Ok, laissons de côté, au moins pour l'instant. Je pourrai éventuellement m'en charger à la toute fin ;)
