### ISSUE TITLE
Traduction Scénario 4 

### ISSUE THREAD

**Issue by e-guenat** [cyrilou242/covid-19#20]
@MaximeBedoin : dans ma fougue de la traduction NextMonths Scenario 0-3, j'ai empiété sur le scenario 4, sans avoir le temps de le signaler dans le trad_notes. Afin de ne pas jeter l'extra aux oubliettes, ci-joint ma contribution, que tu peux choisir de réutiliser ou pas. J'attire ton attention à la phrase suivante:

"Mais c'est exactement ça! "Un confinement n'est pas un remède, c'est juste un retour au début"... **et un nouveau départ est ce dont on a besoin.**

C'est important d'être cohérent avec la trad des scenarios 0-3 (en PR au moment où j'écris) pour  garder l'impact. On peut débattre de l'utilisation de "retour au début", qui est un peu désuet, mais c'est précisément pour laisser le romantique "nouveau départ" pour la punchline citée ci-dessus.

```
###Scenario 4: Tester, Suivre, Isoler

*"Certes, nous \*aurions pu\* faire ce que Taïwan et la Corée du Sud ont fait au début, mais c'est trop tard maintenant. On a manqué le départ."*

Mais c'est exactement ça! "Un confinement n'est pas un remède, c'est juste un retour au début"... **et un nouveau départ est ce dont on a besoin.**

Pour comprendre comment Taïwan et la Corée du Sud ont contenu le COVID-19, de devons comprendre le déroulement typique d'une infection du COVID-19[^timeline]:

[^timeline]: **3 jours en moyenne avant d'être infectieux** “Assuming an incubation period distribution of mean 5.2 days from a separate study of early COVID-19 cases, we inferred that infectiousness started from 2.3 days (95% CI, 0.8–3.0 days) before symptom onset” [He, X., Lau, E.H.Y., Wu, P. et al.](https://www.nature.com/articles/s41591-020-0869-5) Traduction: "En hypothésant une distribution de la période d'incubation d'une moyenne de 5,2 jours à partir d'un autre étude des premiers cas de COVID-19, nous avons inféré que l'inféctiosité commençait à partir de 2.3 jours (IC 95%: 0,8-3,0 jours) avant l'apparition des symptômes" Comprenez: En supposant que les symptômes apparaîssent à 5 jours, l'inféctiosité commence 2 jours avant = l'inféctiosité commence à 3 jours.

  **4 jours en moyenne pour infecter une nouvelle personne:** “The mean [serial] interval was 3.96 days (95% CI 3.53–4.39 days)” [Du Z, Xu X, Wu Y, Wang L, Cowling BJ, Ancel Meyers L](https://wwwnc.cdc.gov/eid/article/26/6/20-0357_article) Traduction: "L'intervalle seriel moyen était de 3.96 jour (IC 95%: 3,53-4,39)"

  **5 jours en moyenne pour déclarer les symptômes** “The median incubation period was estimated to be 5.1 days (95% CI, 4.5 to 5.8 days)” [Lauer SA, Grantz KH, Bi Q, et al](https://annals.org/AIM/FULLARTICLE/2762808/INCUBATION-PERIOD-CORONAVIRUS-DISEASE-2019-COVID-19-FROM-PUBLICLY-REPORTED) Traduction: "La période d'incubation médiane a été estimée à 5,1 jours (IC 95%: 4,5 à 5,8 jours)"

  ![](pics/timeline1.png)

```

**Comment by MaximeBedoin** [comment]
Ok, je vais relire la partie 0-3, comme c'était ce que j'avais traduit dans
un premier temps !

**Comment by e-guenat** [comment]
OK, hésite pas à laisser dans commentaires dans le PR quand tu relis, si tu vois des erreurs/incohérences/oublis, comme ça on fait un review directement !

**Comment by NicoKiaru** [comment]
> On peut débattre de l'utilisation de "retour au début"

Je n'ai pas tout le contexte, mais est-ce que "retour à la case départ" irait aussi?

**Comment by MaximeBedoin** [comment]
Je suis en train ! Est ce que c'est bon si je prépare un bloc notes et que
je l'envoie ?

**Comment by e-guenat** [comment]
@NicoKiaru : c'est top, merci pour l'input. Je vais modifier ça.

@MaximeBedoin : je préfère si tu ajoutes tes commentaires directement sur le PR

**Comment by MaximeBedoin** [comment]
Ok je vais faire ça alors !

**Comment by e-guenat** [comment]
@kephas cette Issue peut t'intéresser
