### ISSUE TITLE
Comment traduire Circuit Breaker ?

### ISSUE THREAD

**Issue by cyrilou242** [cyrilou242/covid-19#22]
tout est dans le titre. L'expression est utilisée quelques fois.

**Comment by e-guenat** [comment]
pour _NextMonths: Scenario 0-3_ j'ai utilisé *coupe-circuit*, qui est je crois la traduction technique (si on écarte le trivial "disjoncteur électrique").

**Comment by sylvainberube** [comment]
@cyrilou242 Je venais aussi de me poser la question.

@e-guenat Donc _"circuit breaker" lockdown_ devient _confinement «coupe-circuit»_, est-ce ça?

**Comment by cyrilou242** [comment]
ok, perso je cherchais quelque chose comme "enrayeur" (si ça vous donne des idées), mais dans le sens "enrayeur bourrin"

**Comment by cyrilou242** [comment]
enrayeur-massue en inventant

**Comment by cyrilou242** [comment]
enrayeur-choc, traitement choc

**Comment by e-guenat** [comment]
@sylvainberube : oui, c'est ça. 

Je viens de trouver cette [source](https://www.lesechos.fr/monde/asie-pacifique/coronavirus-singapour-enclenche-le-disjoncteur-et-inquiete-les-autres-capitales-dasie-1191878) utilisant le terme *disjoncteur* (pas si trivial, finalement). On pourrait utiliser "confinement disjoncteur"

**Comment by cyrilou242** [comment]
c'est bien "disjoncteur“ (entre guillemets), ok pour moi !
