### ISSUE TITLE
uniformiser: Guillemets français

### ISSUE THREAD

**Issue by sylvainberube** [cyrilou242/covid-19#28]
Pour l'instant on a employé les guillemets anglais ("...") et non les guillemets français («...»). Habituellement on utilise les guillemets français en français. Je propose qu'on adopte cette forme. Vous en pensez quoi?

**Comment by e-guenat** [comment]
Je suis ok avec cette suggestion.

**Comment by cyrilou242** [comment]
ok pour moi.
Les guillemets francais prennent pas mal de place, est ce qu'on les mets dans les help box ? (les petits numéros, certaines boites on tendance à être petites en largeur ou a déja avoir beaucoup de lignes - sur Chrome). 
Généralement ce sont des quotes de texte anglais. (puis notre traduction)

**Comment by sylvainberube** [comment]
Je propose de les utiliser aussi dans les help box pour uniformiser.
