### ISSUE TITLE
Traduction Scenario 4

### ISSUE THREAD

**Issue by cyrilou242** [cyrilou242/covid-19#29]
Ne voyant pas de fork d' @kephas, je me dis qu'il n'a peut-être pas vu ton message @MaximeBedoin . 

Si on n'a pas de nouvelles d'ici 48 heures quelqu'un pourra prendre la traduction ?

**Comment by cyrilou242** [comment]
duplicate

**Comment by MaximeBedoin** [comment]
Oui bien sûr, je peux même commencer cet après midi s’il faut !

**Comment by e-guenat** [comment]
Je serais pour avancer directement la traduction si @MaximeBedoin est dispo :) tu avais signalé ton intérêt en premier lieu.
