### ISSUE TITLE
Comment traduire 'waning'

### ISSUE THREAD

**Issue by MaximeBedoin** [cyrilou242/covid-19#30]
la traduction littérale 'en déclin' n'est pas du tout adaptée mais je ne vois pas comment exprimer le concept en français de manière efficace

**Comment by cyrilou242** [comment]
Où est ce que tu as vu le mot ?
Dans la trad on utilise déclin exponentielle à un moment (mais c'était pour decay).

En fonction du contexte juste "diminue/décline" en très simple.

**Comment by sylvainberube** [comment]
Le mot _waning_ apparaît entre autres dans l'image seirs.png.

**Comment by MaximeBedoin** [comment]
Oui c’est dans cette image ... il me semble que le mot en anglais est un
peu plus spécifique, dans l’image je le comprends comme « redevient
susceptible à l’infection » mais c’est très peu efficace comme tournure.

Le mar. 5 mai 2020 à 07:32, Sylvain Bérubé <notifications@github.com> a
écrit :

**Comment by cyrilou242** [comment]
"perte de l'immunité" ? 
"perte d'immunité" ? 
"déclin de l'immunité" ? 

(nominal car les autres expressions seront sous forme nominales: transmission, incubation, guérison)

**Comment by sylvainberube** [comment]
Dans l'image il y a de l'espace pour une longue expression. J'aime bien «perte d'immunité» et «perte de l'immunité».

**Comment by MaximeBedoin** [comment]
Ca me semble bien !

Le mar. 5 mai 2020 à 15:27, Sylvain Bérubé <notifications@github.com> a
écrit :

**Comment by cyrilou242** [comment]
super ! imho "perte de l'immunité"
