### ISSUE TITLE
Epidemiology 101

### ISSUE THREAD

**Issue by vbruttin** [cyrilou242/covid-19#32]
Merci à l'équipe de ce git pour le travail fourni!

En parcourant le README, j'ai relevé que la traduction d'"Epidemiology 101" ne semble pas fixée et je n'ai pas trouvé de discussion dans les Issues, alors voilà...

L'expression est très courante en Amérique du Nord, mais elle me semble peu comprise en Europe. Une traduction possible :  le b.a.-ba de l'épidemiologie (orthographe privilégie sur wiktionnaire). 

Avantage : également une expression, couvre bien la signification de '101'
Inconvénient  :  je ne connaît pas l'étendue ou l'universalité de l'usage de cette expression en francophonie.

**Comment by cyrilou242** [comment]
la traduction a varié en fonction du contexte, nous avons utilisé (de tête):
- l'épidémiologie
- les bases de l'épidémiologie
- introduction à l'épidémiologie
