### ISSUE TITLE
partie Help make a translation

### ISSUE THREAD

**Issue by cyrilou242** [cyrilou242/covid-19#35]
Pour la partie 
```
Translations:
日本語
Español
Magyar
Help make a translation?
```

De l'original, je propose de mettre: 
```
Article original en anglais. 
```
Pas envie de maintenir les liens vers les différentes traductions, et en réalité peu de chance qu'on non francophone tombe sur la version  francaise.

**Comment by e-guenat** [comment]
Oui, je suis d'accord pour faire un seul lien vers la VO.

**Comment by cyrilou242** [comment]
done
