### ISSUE TITLE
uniformiser Test, Trace, Isolate

### ISSUE THREAD

**Issue by donok1** [cyrilou242/covid-19#39]
Peut-être pouvons continuer ici la discussion concernant "Test, Trace, Isolate" :)
Je crois que toute le monde est d'accord pour:
- Test -> Tester, Test ou Tests
- Isolate -> Isoler, Isolement

Trace est débattu entre **Suivre, Suivi** et **Tracer,  #Traçage** #33 

@kephas:
> Si je cherche « suivi de contact » sur Google, sur la première page de résultats, seul le n°8 est à propos de StopCovid.
> 
> Si je cherche « tracage de contact », l'intégralité de la première page de résultats porte sur le _contact tracing_.

@e-guenat
> C'est vrai que le terme "suivi de contact" n'a pas pris (peut-être que "suivi de contact" c'est pour les architectures décentralisées, et "traçage" pour les vilaines solutions centralisée ? :P)
> 
> Blague à part, c'est vrai qu'on devrait s'adapter au consensus et utiliser le terme traçage finalement. Un quality check pour homogénéiser la trad ?

Pour ce qui est des autorités Suisses, elles parlent clairement de "Traçage":
`Dès que le nombre d'infections aura suffisamment diminué en Suisse, les autorités sanitaires cantonales devront recommencer à **tracer** les chaînes de transmission de façon systématique (**traçage** des contacts classique).`

Bien qu'à consonance plus autoritaire, j'entends plus souvent parler d'appli de traçage dans mon entourage, et pense plus proche de ce que les gens connaissent déjà.

**Comment by cyrilou242** [comment]
ok pour tracage perso.

**Comment by e-guenat** [comment]
ok pour traçage aussi.

**Comment by kephas** [comment]
Donc « Test, Traçage, Isolement » ?

**Comment by donok1** [comment]
Je préfère même: "Tester, Tracer, Isoler"
Actif et concis (et rythmé, isolement a trop de syllabes pour être accrocheur :P)

**Comment by cyrilou242** [comment]
préférence pour "Tester, Tracer, Isoler" aussi

(et traçage, isolement va poser problème dans les images c'est un peu long)

**Comment by cyrilou242** [comment]
done
