### ISSUE TITLE
uniformiser covid-19 | COViD-19

### ISSUE THREAD

**Issue by cyrilou242** [cyrilou242/covid-19#41]
cf titre.

perso je préfère COVID

**Comment by donok1** [comment]
Moi pareil

**Comment by e-guenat** [comment]
Moi aussi.

**Comment by kephas** [comment]
Mais les médias français utilisent très largement « Covid-19 », non ?

**Comment by sylvainberube** [comment]
Au [Québec](https://www.quebec.ca/sante/problemes-de-sante/a-z/coronavirus-2019/) et au [Canada](https://www.canada.ca/fr/sante-publique/services/maladies/2019-nouveau-coronavirus/symptomes.html), COVID-19 est principalement employé, tant du côté des médias que des gouvernements.

**Comment by cyrilou242** [comment]
done
