### ISSUE TITLE
Pour info, un article qui reprend les simulations

### ISSUE THREAD

**Issue by NicoKiaru** [cyrilou242/covid-19#43]
Si ça peut etre utile, il y a certaines  des simulations incluses et traduites.

https://www.letemps.ch/sciences/questce-attend-un-guide-covid19-alarmer-donner-espoir

**Comment by NicoKiaru** [comment]
"un format interactif bourré d’un humour anglo-saxon intraduisible." C'est pour vous les cocos ;-)

**Comment by cyrilou242** [comment]
leur demander de mettre un lien vers la trad plutot que "help pour la trad" à la fin quand c'est prêt de notre côté ?
