### ISSUE TITLE
Uniformiser : What happens next ?

### ISSUE THREAD

**Issue by donok1** [cyrilou242/covid-19#46]
Je crois avoir perdu le fil des discussions entre les pictures et l'intro :)
J'ai trouvé les 2 versions suivantes:

- Ce qui nous attend.
- Et ensuite ?

Perso, je préfère "Et ensuite ?", plus court et accrocheur, surtout pour la thumbnail

**Comment by cyrilou242** [comment]
Chaud pour "Et ensuite ?"

**Comment by cyrilou242** [comment]
done
