### ISSUE TITLE
nowrap au niveau des ponctuations

### ISSUE THREAD

**Issue by cyrilou242** [cyrilou242/covid-19#49]
rajouter des `nowrap` pour éviter des ponctuations seules sur une ligne

**Comment by donok1** [comment]
j'ai fait ca #51  avec des espace insécable, Unicode `00A0` https://en.wikipedia.org/wiki/Non-breaking_space
Le rendu est correcte chez moi dans l'HTML, je suppose que c'est pas un problème lors de la conversion md->html.

**Comment by cyrilou242** [comment]
super !
