### ISSUE TITLE
uniformiser r<1

### ISSUE THREAD

**Issue by cyrilou242** [cyrilou242/covid-19#50]
il y a des `R < 1` et des `R<1` --> uniformiser

**Comment by donok1** [comment]
dans 1 min :)

**Comment by donok1** [comment]
j'ai uniformisé avec `R < 1` (espace insécable de nouveau... dommage qu'ils ne soit pas visible ici ^^), c'était le plus répandu ;)

**Comment by cyrilou242** [comment]
top
