### ISSUE TITLE
Push la traduction sur ncase.me ?

### ISSUE THREAD

**Issue by donok1** [cyrilou242/covid-19#58]
@cyrilou242, comment ça va ?
Tu veux faire une pull request à Nicky ?

**Comment by cyrilou242** [comment]
très occupé dernièrement, j'essaie de faire ça demain (mais n'importe qui peut le faire, en fait c'est très légèrement plus compliqué pour moi puisqu'il faut que je pull le master de ncase dans une autre branche chez moi qui ne soit pas master (rien de bien compliqué en vrai))

**Comment by cyrilou242** [comment]
see https://github.com/ncase/covid-19/pull/74
