### ISSUE TITLE
Retranscription du texte contenu dans les images png

### ISSUE THREAD

**Issue by NicoKiaru** [cyrilou242/covid-19#7]
Pour info je démarre la retranscription (pas la traduction) du texte contenu dans les images, et je le mettrai ici:

https://github.com/cyrilou242/covid-19/blob/master/pics/PICS_TRANSLATION.md

**Comment by sylvainberube** [comment]
Super, de mon côté je vois à l'identification des polices.

**Comment by sylvainberube** [comment]
@NicoKiaru  Je vois que tu as contacté ncase pour l'identification des polices et la récupération des fichiers modifiables, c'est excellent.

**Comment by cyrilou242** [comment]
Salut, pour les comics strip il y a des traductions déjà disponibles ici : https://github.com/DP-3T/documents/tree/master/public_engagement/cartoon/fr.
Le contributeur pourra peut-être vous aider :)

**Comment by sylvainberube** [comment]
Merci pour la référence @cyrilou242. Il y est mentionné que les polices sont Patrick Hand et Open Sans.

**Comment by sylvainberube** [comment]
@NicoKiaru J'ai poursuivi le travail, merci d'avoir lancé ça.

**Comment by cyrilou242** [comment]
done ! Bien joué @sylvainberube @NicoKiaru @donok1 !
